<a href="https://colab.research.google.com/github/nataliashalaeva/ml/blob/main/lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Лабораторная работа №1
Пакет Numpy

In [18]:
import numpy as np

In [2]:
from numpy import random

Создать вектор (одномерный массив) размера 10, заполненный
нулями

In [3]:
v1 = np.zeros(10)
print(v1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Создать вектор (одномерный массив) размера 10, заполненный
нулями, пятый элемент должен быть равен 1

In [4]:
v2 = np.zeros(10)
v2[4] = 1
print(v2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Создать вектор (одномерный массив) размера 20. Заполнить его
случайными значениями. Найти индексы ненулевых элементов

In [20]:
v3 = np.random.rand(20)
print(v3)
print(np.nonzero(v3))

[0.59981771 0.7536292  0.09919824 0.10631524 0.36677032 0.45630618
 0.23865493 0.15365936 0.78894669 0.51950108 0.79112867 0.2982125
 0.00637645 0.38863873 0.98750901 0.47949803 0.03723172 0.89546502
 0.10156712 0.94193706]
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),)


Создать массив 3x3x3. Заполнить его случайными значениями

In [6]:
v4 = np.random.rand(3, 3, 3)
print(v3)

[0.2411213  0.05822097 0.24894237 0.40109481 0.31557758 0.79349287
 0.0969652  0.56166215 0.84566191 0.58889812 0.29144759 0.85196217
 0.13317934 0.909078   0.74326412 0.2174141  0.92541368 0.58685805
 0.50239216 0.18426797]


Создать вектор (одномерный массив) размера 10. Заполнить его
случайными значениями. Найти среднее значение всех элементов

In [19]:
v5 = np.random.rand(10)
print(v5)
print(np.mean(v5))

[0.92102421 0.49562299 0.16765158 0.94140148 0.13195758 0.0428089
 0.60108808 0.35576673 0.971039   0.94572274]
0.5574083285047794


Создать две матрицы 5x3 и 3x2. Найти их произведение.

In [25]:
v6_1 = np.random.randint(10, size=[5, 3])
v6_2 = np.random.randint(10, size =[3, 2])
print(v6_1)
print(v6_2)
print(np.dot(v6_1, v6_2))

[[1 4 2]
 [2 8 7]
 [0 8 3]
 [6 8 9]
 [9 9 1]]
[[3 1]
 [1 4]
 [2 4]]
[[11 25]
 [28 62]
 [14 44]
 [44 74]
 [38 49]]


Создать две матрицы 4x4 и 4x4. Найти их произведение. Найти
диагональные элементы произведения матриц

In [27]:
v7_1 = np.random.randint(10, size =[4, 4])
v7_2 = np.random.randint(10, size =[4, 4])
v7 = np.dot(v7_1, v7_2)
print(v7_1)
print(v7_2)
print(v7)
print(np.diagonal(v7))

[[7 0 7 4]
 [0 9 0 3]
 [7 7 9 2]
 [9 6 2 1]]
[[7 8 1 1]
 [6 6 7 7]
 [5 9 4 0]
 [4 8 1 0]]
[[100 151  39   7]
 [ 66  78  66  63]
 [144 195  94  56]
 [113 134  60  51]]
[100  78  94  51]


Создать вектор (одномерный массив) размера 20. Заполнить его
случайными значениями. Заменить максимальный элемент на ноль

In [10]:
v8 = np.random.randint(50, size = 20)
print(v8)
v8[v8 == v8.max()] = 0
print(v8)

[38  8 29 39 29 35 35 16 46 29 31  2 14 17 26 21 23 20 17 34]
[38  8 29 39 29 35 35 16  0 29 31  2 14 17 26 21 23 20 17 34]


Создать вектор (одномерный массив) размера 20. Заполнить его
случайными значениями. Напечатать все значения в массиве без повторений.

In [28]:
v9 = np.random.randint(10, size = 20)
print(v9)
print(np.unique(v9))

[7 7 7 9 9 3 3 3 0 7 7 5 4 4 9 1 8 8 7 7]
[0 1 3 4 5 7 8 9]


Создать матрицу. Отнять среднее из каждой строки в матрице

In [29]:
v10 = np.random.randint(10, size = [4, 4])
print(v10)
v10 = v10 - np.mean(v10)
print(v10)

[[2 2 5 7]
 [4 8 4 9]
 [8 6 6 5]
 [6 7 7 1]]
[[-3.4375 -3.4375 -0.4375  1.5625]
 [-1.4375  2.5625 -1.4375  3.5625]
 [ 2.5625  0.5625  0.5625 -0.4375]
 [ 0.5625  1.5625  1.5625 -4.4375]]


Создать матрицу. Поменять две строки в матрице

In [13]:
v11 = np.random.randint(10, size = [4, 4])
print(v11)
v11[[0, 1]] = v11[[1, 0]]
print(v11)

[[3 4 3 7]
 [8 6 2 8]
 [8 9 8 5]
 [6 7 5 9]]
[[8 6 2 8]
 [3 4 3 7]
 [8 9 8 5]
 [6 7 5 9]]


Создать вектор (одномерный массив) размера 20. Заполнить его
случайными значениями. Найти n наибольших значений в векторе

In [14]:
v12 = np.random.randint(10, size=20)
print(v12)
np.sort(v12)[-3::]

[4 1 3 2 1 5 9 1 6 4 7 8 1 7 7 7 4 9 4 8]


array([8, 9, 9])

Создать матрицу размера 5x5 и заполнить ее случайными целыми
числами от 1 до 10. Найти сумму элементов каждой строки.

In [30]:
v13 = np.random.randint(1, 11, size = [5, 5])
print(v13)
np.sum(v13, axis = 1)

[[ 9 10  2  3  7]
 [10  9  8  4  1]
 [ 2 10  5  6 10]
 [ 5 10  1  6  9]
 [10  8  6  6  2]]


array([31, 32, 33, 31, 32])

Создать вектор (одномерный массив) размера 10. Заполнить его
случайными значениями от -1 до 1. Заменить отрицательные значения на -1,
положительные на 1, и оставить нулевые значения без изменений.

In [33]:
v14 = np.random.rand(10) *2-1
print(v14)
v14 = np.where(v14 > 0, 1, -1)
print(v14)

[-0.29172336 -0.97554842 -0.01267307 -0.91932847 -0.52576479 -0.59019615
 -0.62942266 -0.09595803 -0.90361995  0.24423674]
[-1 -1 -1 -1 -1 -1 -1 -1 -1  1]


Создать вектор (одномерный массив) размера 12 и заполнить его
случайными значениями от 1 до 100. Разделить вектор на 3 равные части и
найти сумму элементов в каждой части.

In [32]:
v15 = np.random.randint(1, 101, size=12)
print(v15)
v15_1 = np.split(v15, 3)
print(np.sum(v15_1, axis=1))

[96 94 48 34 74 23 75 24 18 26  7 78]
[272 196 129]
